# permissions for end users to edit ipmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipmapping-editor-role
rules:
- apiGroups:
  - change.group.change.me.later
  resources:
  - ipmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - change.group.change.me.later
  resources:
  - ipmappings/status
  verbs:
  - get
