---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - change.group.change.me.later
  resources:
  - ipmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - change.group.change.me.later
  resources:
  - ipmappings/finalizers
  verbs:
  - update
- apiGroups:
  - change.group.change.me.later
  resources:
  - ipmappings/status
  verbs:
  - get
  - patch
  - update
